export const STRINGS = {
  APP_NAME: 'Pedestal: Speech Coach',
  APP_SUBTITLE: 'Reduce Filler Words Faster',

  ONBOARDING: {
    SCREEN_1_TITLE: 'Speak with confidence',
    SCREEN_1_BODY: 'Record yourself and get instant AI feedback',
    SCREEN_2_TITLE: 'Know what to fix',
    SCREEN_2_BODY: 'Not just what\'s wrong, but exactly how to improve',
    SCREEN_3_TITLE: 'Track your growth',
    SCREEN_3_BODY: 'Watch your skills improve session by session',
    NEXT: 'Next',
    SKIP: 'Skip',
    GET_STARTED: 'Get Started',
  },

  TABS: {
    PRACTICE: 'Practice',
    PROGRESS: 'Progress',
    LEARN: 'Learn',
    SETTINGS: 'Settings',
  },

  PRACTICE: {
    TAP_TO_START: 'Tap to start practicing',
    RECORDING: 'Recording...',
    TAP_TO_STOP: 'Tap to stop',
    MIN_DURATION: 'Record at least 10 seconds',
    ANALYZING: 'Analyzing your speech...',
    IMPROMPTU_TITLE: 'Impromptu Mode',
    IMPROMPTU_BODY: 'Get a random topic and speak with no preparation',
  },

  IMPROMPTU: {
    TITLE: 'Impromptu Mode',
    YOUR_TOPIC: 'Your Topic',
    THINK_TIME: 'Think Time',
    RECORDING_STARTS: 'Recording starts automatically',
    NEW_TOPIC: 'New Topic',
    RECORDING: 'Speaking...',
    TAP_TO_STOP: 'Tap to finish',
    ANALYZING: 'Analyzing your speech...',
    MIN_DURATION: 'Speak for at least 10 seconds',
  },

  RESULTS: {
    TITLE: 'Session Results',
    CLARITY_SCORE: 'Clarity Score',
    WORDS_PER_MINUTE: 'Words / Min',
    FILLER_WORDS: 'Filler Words',
    DURATION: 'Duration',
    WPM_GOOD: '130-160 is ideal',
    TRANSCRIPT_TITLE: 'Your Transcript',
    PRACTICE_AGAIN: 'Practice Again',
    VIEW_TIPS: 'View Tips',
    TIPS_TITLE: 'Tips for You',
    TIP_SLOW_DOWN: 'Try slowing down. Pausing between thoughts sounds more confident than rushing.',
    TIP_SPEED_UP: 'You spoke slowly. Try increasing your energy and pace slightly.',
    TIP_FILLERS: 'Replace filler words with a brief pause. Silence sounds more powerful than "um".',
    TIP_CLARITY: 'Great clarity! Keep practicing to maintain this level.',
    TIP_GOOD_PACE: 'Your pace is in the ideal range. Keep it up!',
  },

  PROGRESS: {
    TITLE: 'Your Progress',
    EMPTY_TITLE: 'No sessions yet',
    EMPTY_BODY: 'Complete your first session to see your progress here',
    TOTAL_SESSIONS: 'Sessions',
    AVG_CLARITY: 'Avg Clarity',
    AVG_WPM: 'Avg WPM',
    TOTAL_TIME: 'Practice Time',
    RECENT_SESSIONS: 'Recent Sessions',
    IMPROVEMENT: 'Clarity Over Time',
    CHART_MIN_SESSIONS: 'Complete 2+ sessions to see your trend',
  },

  LEARN: {
    TITLE: 'Fix-It Drills',
    EXERCISES: 'exercises',
    DIFFICULTY_BEGINNER: 'Beginner',
    DIFFICULTY_INTERMEDIATE: 'Intermediate',
    DIFFICULTY_ADVANCED: 'Advanced',
  },

  DRILL: {
    TIP_LABEL: 'Technique',
    PROMPT_LABEL: 'Read This Aloud',
    RECORD_CTA: 'Record & Practice',
    ANALYZING: 'Checking your performance...',
    RESULT_TITLE: 'Drill Result',
    PASSED: 'Passed!',
    NEEDS_WORK: 'Keep Practicing',
    YOUR_SCORE: 'Your Score',
    TARGET: 'Target',
    TRY_AGAIN: 'Try Again',
    BACK_TO_DRILLS: 'Back to Drills',
    MIN_DURATION: 'Record at least 10 seconds',
  },

  CONSENT: {
    TITLE: 'Speech Analysis',
    BODY: 'Pedestal uses OpenAI\'s speech-to-text service to transcribe and analyze your recordings. Your audio is sent to OpenAI for processing. No recordings are stored on their servers after processing.',
    AGREE: 'I Agree',
    DECLINE: 'Not Now',
    REQUIRED: 'Speech analysis requires sending audio to OpenAI. You can enable this in Settings.',
  },

  SETTINGS: {
    TITLE: 'Settings',
    ACCOUNT: 'Account',
    SUBSCRIPTION: 'Subscription',
    MANAGE_SUBSCRIPTION: 'Manage Subscription',
    RESTORE_PURCHASES: 'Restore Purchases',
    RESTORE_SUCCESS: 'Purchases restored!',
    RESTORE_NONE: 'No previous purchases found.',
    RESTORE_ERROR: 'Could not restore purchases. Please try again.',
    NOTIFICATIONS: 'Notifications',
    PRIVACY_POLICY: 'Privacy Policy',
    TERMS: 'Terms of Use',
    DELETE_ACCOUNT: 'Delete All Data',
    DELETE_CONFIRM_TITLE: 'Delete All Data?',
    DELETE_CONFIRM_BODY: 'This will permanently delete all your sessions, progress, and preferences. This cannot be undone.',
    DELETE_CONFIRM: 'Delete Everything',
    CANCEL: 'Cancel',
    RATE_APP: 'Rate Pedestal',
    APP_VERSION: 'App Version',
    GENERAL: 'General',
    SUPPORT: 'Support',
    DANGER: 'Danger Zone',
  },

  PAYWALL: {
    TITLE: 'Speak with confidence',
    SUBTITLE: 'Join thousands improving their speaking skills',
    MONTHLY_LABEL: 'Monthly',
    MONTHLY_PRICE: '£4.99/month',
    ANNUAL_LABEL: 'Annual',
    ANNUAL_PRICE: '£29.99/year',
    ANNUAL_SAVING: 'Save 50%',
    LIFETIME_LABEL: 'Lifetime',
    LIFETIME_PRICE: '£49.99 one-time',
    CTA: 'Try free for 3 days',
    RESTORE: 'Restore Purchases',
    TERMS: 'Cancel anytime. You won\'t be charged until the trial ends.',
    LEGAL: 'Subscription automatically renews unless cancelled at least 24 hours before the end of the current period.',
    FEATURE_RECORDINGS: 'Unlimited speech recordings',
    FEATURE_AI: 'AI-powered analysis and coaching',
    FEATURE_DRILLS: '15+ Fix-It drills and exercises',
    FEATURE_IMPROMPTU: 'Impromptu mode with 50+ topics',
    LOADING: 'Processing...',
    ERROR: 'Something went wrong. Please try again.',
    RESTORING: 'Restoring purchases...',
    RESTORED: 'Purchases restored!',
    NO_PURCHASES: 'No previous purchases found.',
  },

  ERRORS: {
    RECORDING_FAILED: 'Recording failed. Please try again.',
    NETWORK_ERROR: 'No internet connection. Some features may be limited.',
    SUBSCRIPTION_ERROR: 'Unable to verify subscription. Please try again.',
    NO_API_KEY: 'Speech analysis not configured. Check your API key.',
    TRANSCRIPTION_FAILED: 'Could not analyze speech. Please try again.',
    SOMETHING_WRONG: 'Something went wrong',
    ERROR_BOUNDARY_BODY: 'The app encountered an unexpected error. Please restart to continue.',
    RESTART: 'Restart',
  },
} as const;
